package it.csi.gestionepazienti.pazientiweb.dto;

public class Asl extends AbstractDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asl.cod_regione
	 * @mbg.generated
	 */
	private String codRegione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asl.cod_asl
	 * @mbg.generated
	 */
	private String codAsl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asl.desc_regione
	 * @mbg.generated
	 */
	private String descRegione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asl.desc_asl
	 * @mbg.generated
	 */
	private String descAsl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asl.desc_asl_estesa
	 * @mbg.generated
	 */
	private String descAslEstesa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column asl.id_asr
	 * @mbg.generated
	 */
	private Long idAsr;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asl.cod_regione
	 * @return  the value of asl.cod_regione
	 * @mbg.generated
	 */
	public String getCodRegione() {
		return codRegione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asl.cod_regione
	 * @param codRegione  the value for asl.cod_regione
	 * @mbg.generated
	 */
	public void setCodRegione(String codRegione) {
		this.codRegione = codRegione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asl.cod_asl
	 * @return  the value of asl.cod_asl
	 * @mbg.generated
	 */
	public String getCodAsl() {
		return codAsl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asl.cod_asl
	 * @param codAsl  the value for asl.cod_asl
	 * @mbg.generated
	 */
	public void setCodAsl(String codAsl) {
		this.codAsl = codAsl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asl.desc_regione
	 * @return  the value of asl.desc_regione
	 * @mbg.generated
	 */
	public String getDescRegione() {
		return descRegione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asl.desc_regione
	 * @param descRegione  the value for asl.desc_regione
	 * @mbg.generated
	 */
	public void setDescRegione(String descRegione) {
		this.descRegione = descRegione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asl.desc_asl
	 * @return  the value of asl.desc_asl
	 * @mbg.generated
	 */
	public String getDescAsl() {
		return descAsl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asl.desc_asl
	 * @param descAsl  the value for asl.desc_asl
	 * @mbg.generated
	 */
	public void setDescAsl(String descAsl) {
		this.descAsl = descAsl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asl.desc_asl_estesa
	 * @return  the value of asl.desc_asl_estesa
	 * @mbg.generated
	 */
	public String getDescAslEstesa() {
		return descAslEstesa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asl.desc_asl_estesa
	 * @param descAslEstesa  the value for asl.desc_asl_estesa
	 * @mbg.generated
	 */
	public void setDescAslEstesa(String descAslEstesa) {
		this.descAslEstesa = descAslEstesa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column asl.id_asr
	 * @return  the value of asl.id_asr
	 * @mbg.generated
	 */
	public Long getIdAsr() {
		return idAsr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column asl.id_asr
	 * @param idAsr  the value for asl.id_asr
	 * @mbg.generated
	 */
	public void setIdAsr(Long idAsr) {
		this.idAsr = idAsr;
	}
}