package it.csi.gestionepazienti.pazientiweb.dto;

public class MedicoSoggetto extends AbstractDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_medico_soggetto.id_medico
     *
     * @mbg.generated
     */
    private Long idMedico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_medico_soggetto.id_soggetto
     *
     * @mbg.generated
     */
    private Long idSoggetto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_medico_soggetto.id_medico
     *
     * @return the value of r_medico_soggetto.id_medico
     *
     * @mbg.generated
     */
    public Long getIdMedico() {
        return idMedico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_medico_soggetto.id_medico
     *
     * @param idMedico the value for r_medico_soggetto.id_medico
     *
     * @mbg.generated
     */
    public void setIdMedico(Long idMedico) {
        this.idMedico = idMedico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_medico_soggetto.id_soggetto
     *
     * @return the value of r_medico_soggetto.id_soggetto
     *
     * @mbg.generated
     */
    public Long getIdSoggetto() {
        return idSoggetto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_medico_soggetto.id_soggetto
     *
     * @param idSoggetto the value for r_medico_soggetto.id_soggetto
     *
     * @mbg.generated
     */
    public void setIdSoggetto(Long idSoggetto) {
        this.idSoggetto = idSoggetto;
    }
}