package it.csi.gestionepazienti.pazientiweb.mapper.postiletto.extend;

import it.csi.gestionepazienti.pazientiweb.dto.postiletto.Area;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface AreaMapper {


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbg.generated
	 */
	@Select({ "select", "id_area, id_struttura, id_d_area, nome, responsabile, riferimento, stato_validita",
			"from area", "where id_struttura = #{idStruttura,jdbcType=VARCHAR} and (stato_validita='ATTIVO' or stato_validita is null)" })
	@Results({ @Result(column = "id_area", property = "idArea", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "id_struttura", property = "idStruttura", jdbcType = JdbcType.VARCHAR),
			@Result(column = "id_d_area", property = "idDArea", jdbcType = JdbcType.VARCHAR),
			@Result(column = "nome", property = "nome", jdbcType = JdbcType.VARCHAR),
			@Result(column = "responsabile", property = "responsabile", jdbcType = JdbcType.VARCHAR),
			@Result(column = "riferimento", property = "riferimento", jdbcType = JdbcType.VARCHAR),
			@Result(column = "stato_validita", property = "statoValidita", jdbcType = JdbcType.VARCHAR) })
	List<Area> selectByIdStrutturaValid(String idStruttura);


}