package it.csi.gestionepazienti.pazientiweb.mapper.extend;

import java.util.List;

import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

import it.csi.gestionepazienti.pazientiweb.dto.custom.LaboratorioCompleto;
import it.csi.gestionepazienti.pazientiweb.mapper.generated.BaseLaboratorioMapper;

public interface LaboratorioMapper extends BaseLaboratorioMapper{

	
	

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table laboratorio
	 * @mbg.generated
	 */
	@Select({
			"select" , 
			" laboratorio.id_laboratorio, descrizione, sigla_laboratorio, capacita_giornaliera,coalesce(tamponi_da_lavorare,0) tamponi_da_lavorare" , 
			"from laboratorio" , 
			"left join (" , 
			"SELECT" , 
			"id_laboratorio," , 
			"COUNT(id_tampone) AS tamponi_da_lavorare" , 
			"FROM sset_meta_toolchain.tampone" , 
			"WHERE (id_laboratorio <> 6) AND (data_test IS NULL) AND (tampone_autorizzato ='SI')" , 
			"GROUP BY id_laboratorio) tamp on laboratorio.id_laboratorio = tamp.id_laboratorio" , 
		})
	@Results({ @Result(column = "id_laboratorio", property = "idLaboratorio", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "descrizione", property = "descrizione", jdbcType = JdbcType.VARCHAR),
			@Result(column = "sigla_laboratorio", property = "siglaLaboratorio", jdbcType = JdbcType.VARCHAR),
			@Result(column = "capacita_giornaliera", property = "capacitaGiornaliera", jdbcType = JdbcType.INTEGER),
			@Result(column = "tamponi_da_lavorare", property = "tamponiDaLavorare", jdbcType = JdbcType.INTEGER),
			})
	List<LaboratorioCompleto> selectAllWithCarico();

}
