package it.csi.gestionepazienti.pazientiweb.dto.postiletto;

import it.csi.gestionepazienti.pazientiweb.dto.AbstractDto;

public class DecodeArea extends AbstractDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_area.id_d_area
	 * @mbg.generated
	 */
	private String idDArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column d_area.nome
	 * @mbg.generated
	 */
	private String nome;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_area.id_d_area
	 * @return  the value of d_area.id_d_area
	 * @mbg.generated
	 */
	public String getIdDArea() {
		return idDArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_area.id_d_area
	 * @param idDArea  the value for d_area.id_d_area
	 * @mbg.generated
	 */
	public void setIdDArea(String idDArea) {
		this.idDArea = idDArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column d_area.nome
	 * @return  the value of d_area.nome
	 * @mbg.generated
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column d_area.nome
	 * @param nome  the value for d_area.nome
	 * @mbg.generated
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}
}