package it.csi.gestionepazienti.pazientiweb.dto.postiletto;

import it.csi.gestionepazienti.pazientiweb.dto.AbstractDto;
import java.util.Date;

public class Disponibilita extends AbstractDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column disponibilita.id_disponibilita
	 * @mbg.generated
	 */
	private Integer idDisponibilita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column disponibilita.id_area
	 * @mbg.generated
	 */
	private Integer idArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column disponibilita.data_evento
	 * @mbg.generated
	 */
	private Date dataEvento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column disponibilita.tipo_operazione
	 * @mbg.generated
	 */
	private String tipoOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column disponibilita.posti_target
	 * @mbg.generated
	 */
	private Integer postiTarget;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column disponibilita.posti_disponibili
	 * @mbg.generated
	 */
	private Integer postiDisponibili;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column disponibilita.posti_occupati
	 * @mbg.generated
	 */
	private Integer postiOccupati;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column disponibilita.flag_valido
	 * @mbg.generated
	 */
	private String flagValido;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column disponibilita.utente_inserimento
	 * @mbg.generated
	 */
	private String utenteInserimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column disponibilita.data_inserimento
	 * @mbg.generated
	 */
	private Date dataInserimento;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column disponibilita.id_disponibilita
	 * @return  the value of disponibilita.id_disponibilita
	 * @mbg.generated
	 */
	public Integer getIdDisponibilita() {
		return idDisponibilita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column disponibilita.id_disponibilita
	 * @param idDisponibilita  the value for disponibilita.id_disponibilita
	 * @mbg.generated
	 */
	public void setIdDisponibilita(Integer idDisponibilita) {
		this.idDisponibilita = idDisponibilita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column disponibilita.id_area
	 * @return  the value of disponibilita.id_area
	 * @mbg.generated
	 */
	public Integer getIdArea() {
		return idArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column disponibilita.id_area
	 * @param idArea  the value for disponibilita.id_area
	 * @mbg.generated
	 */
	public void setIdArea(Integer idArea) {
		this.idArea = idArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column disponibilita.data_evento
	 * @return  the value of disponibilita.data_evento
	 * @mbg.generated
	 */
	public Date getDataEvento() {
		return dataEvento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column disponibilita.data_evento
	 * @param dataEvento  the value for disponibilita.data_evento
	 * @mbg.generated
	 */
	public void setDataEvento(Date dataEvento) {
		this.dataEvento = dataEvento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column disponibilita.tipo_operazione
	 * @return  the value of disponibilita.tipo_operazione
	 * @mbg.generated
	 */
	public String getTipoOperazione() {
		return tipoOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column disponibilita.tipo_operazione
	 * @param tipoOperazione  the value for disponibilita.tipo_operazione
	 * @mbg.generated
	 */
	public void setTipoOperazione(String tipoOperazione) {
		this.tipoOperazione = tipoOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column disponibilita.posti_target
	 * @return  the value of disponibilita.posti_target
	 * @mbg.generated
	 */
	public Integer getPostiTarget() {
		return postiTarget;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column disponibilita.posti_target
	 * @param postiTarget  the value for disponibilita.posti_target
	 * @mbg.generated
	 */
	public void setPostiTarget(Integer postiTarget) {
		this.postiTarget = postiTarget;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column disponibilita.posti_disponibili
	 * @return  the value of disponibilita.posti_disponibili
	 * @mbg.generated
	 */
	public Integer getPostiDisponibili() {
		return postiDisponibili;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column disponibilita.posti_disponibili
	 * @param postiDisponibili  the value for disponibilita.posti_disponibili
	 * @mbg.generated
	 */
	public void setPostiDisponibili(Integer postiDisponibili) {
		this.postiDisponibili = postiDisponibili;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column disponibilita.posti_occupati
	 * @return  the value of disponibilita.posti_occupati
	 * @mbg.generated
	 */
	public Integer getPostiOccupati() {
		return postiOccupati;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column disponibilita.posti_occupati
	 * @param postiOccupati  the value for disponibilita.posti_occupati
	 * @mbg.generated
	 */
	public void setPostiOccupati(Integer postiOccupati) {
		this.postiOccupati = postiOccupati;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column disponibilita.flag_valido
	 * @return  the value of disponibilita.flag_valido
	 * @mbg.generated
	 */
	public String getFlagValido() {
		return flagValido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column disponibilita.flag_valido
	 * @param flagValido  the value for disponibilita.flag_valido
	 * @mbg.generated
	 */
	public void setFlagValido(String flagValido) {
		this.flagValido = flagValido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column disponibilita.utente_inserimento
	 * @return  the value of disponibilita.utente_inserimento
	 * @mbg.generated
	 */
	public String getUtenteInserimento() {
		return utenteInserimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column disponibilita.utente_inserimento
	 * @param utenteInserimento  the value for disponibilita.utente_inserimento
	 * @mbg.generated
	 */
	public void setUtenteInserimento(String utenteInserimento) {
		this.utenteInserimento = utenteInserimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column disponibilita.data_inserimento
	 * @return  the value of disponibilita.data_inserimento
	 * @mbg.generated
	 */
	public Date getDataInserimento() {
		return dataInserimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column disponibilita.data_inserimento
	 * @param dataInserimento  the value for disponibilita.data_inserimento
	 * @mbg.generated
	 */
	public void setDataInserimento(Date dataInserimento) {
		this.dataInserimento = dataInserimento;
	}
}