package it.csi.gestionepazienti.pazientiweb.dto.postiletto;

import it.csi.gestionepazienti.pazientiweb.dto.AbstractDto;
import java.util.Date;

public class StatoArea extends AbstractDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_area.id_area
	 * @mbg.generated
	 */
	private Integer idArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_area.data_evento
	 * @mbg.generated
	 */
	private Date dataEvento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column s_area.stato_validita
	 * @mbg.generated
	 */
	private String statoValidita;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_area.id_area
	 * @return  the value of s_area.id_area
	 * @mbg.generated
	 */
	public Integer getIdArea() {
		return idArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_area.id_area
	 * @param idArea  the value for s_area.id_area
	 * @mbg.generated
	 */
	public void setIdArea(Integer idArea) {
		this.idArea = idArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_area.data_evento
	 * @return  the value of s_area.data_evento
	 * @mbg.generated
	 */
	public Date getDataEvento() {
		return dataEvento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_area.data_evento
	 * @param dataEvento  the value for s_area.data_evento
	 * @mbg.generated
	 */
	public void setDataEvento(Date dataEvento) {
		this.dataEvento = dataEvento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column s_area.stato_validita
	 * @return  the value of s_area.stato_validita
	 * @mbg.generated
	 */
	public String getStatoValidita() {
		return statoValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column s_area.stato_validita
	 * @param statoValidita  the value for s_area.stato_validita
	 * @mbg.generated
	 */
	public void setStatoValidita(String statoValidita) {
		this.statoValidita = statoValidita;
	}
}